
import { GespraechsEintrag, Muster, Emotionalitaet, Kontext, VerantwortungUebernommen } from './types';

export const MOCK_DATA: GespraechsEintrag[] = [
  { gespraechsId: "001", sprecher: "Person A", text: "Ich habe das so gemacht, weil...", kontext: Kontext.Konflikt, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-01T10:00:00Z" },
  { gespraechsId: "001", sprecher: "Person B", text: "Wer weiß, was du damals gemacht hast.", kontext: Kontext.Konflikt, muster: Muster.Projektion, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Hoch, datum: "2023-10-01T10:01:00Z" },
  { gespraechsId: "002", sprecher: "Teamleiter", text: "Das Ergebnis war nicht optimal. Was sind deine Gedanken dazu?", kontext: Kontext.Feedback, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-02T14:00:00Z" },
  { gespraechsId: "002", sprecher: "Person C", text: "Naja, die Anforderungen waren ja auch unklar.", kontext: Kontext.Feedback, muster: Muster.Relativierung, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-02T14:02:00Z" },
  { gespraechsId: "003", sprecher: "Person B", text: "Wir sollten das Projekt so starten.", kontext: Kontext.Planung, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-03T09:00:00Z" },
  { gespraechsId: "003", sprecher: "Person A", text: "Das erinnert mich an das letzte Projekt, das du geleitet hast. Das ging ja auch schief.", kontext: Kontext.Planung, muster: Muster.Rueckgriff, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-03T09:05:00Z" },
  { gespraechsId: "004", sprecher: "Person C", text: "Ich übernehme die Verantwortung für den Fehler.", kontext: Kontext.Konflikt, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-04T11:00:00Z" },
  { gespraechsId: "004", sprecher: "Teamleiter", text: "Gut, lass uns eine Lösung finden.", kontext: Kontext.Konflikt, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-04T11:01:00Z" },
  { gespraechsId: "005", sprecher: "Person A", text: "Warum wurde ich nicht informiert?", kontext: Kontext.Allgemein, muster: Muster.Schuldabwehr, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Hoch, datum: "2023-10-05T15:30:00Z" },
  { gespraechsId: "005", sprecher: "Person B", text: "Du warst doch im Meeting, als das besprochen wurde.", kontext: Kontext.Allgemein, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-05T15:31:00Z" },
  { gespraechsId: "006", sprecher: "Teamleiter", text: "Dein Beitrag war sehr wertvoll.", kontext: Kontext.Feedback, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-06T16:00:00Z" },
  { gespraechsId: "006", sprecher: "Person A", text: "Danke, ich habe mein Bestes gegeben.", kontext: Kontext.Feedback, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-06T16:01:00Z" },
  { gespraechsId: "007", sprecher: "Person C", text: "Das ist nicht meine Aufgabe.", kontext: Kontext.Konflikt, muster: Muster.Schuldabwehr, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-09T13:20:00Z" },
  { gespraechsId: "007", sprecher: "Person A", text: "Aber du bist doch der Experte dafür.", kontext: Kontext.Konflikt, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-09T13:21:00Z" },
  { gespraechsId: "007", sprecher: "Person C", text: "Frag doch Person B, die hat doch immer Zeit.", kontext: Kontext.Konflikt, muster: Muster.Projektion, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-09T13:22:00Z" },
  { gespraechsId: "008", sprecher: "Person B", text: "Der Zeitplan ist unrealistisch.", kontext: Kontext.Planung, muster: Muster.Relativierung, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-10T10:00:00Z" },
  { gespraechsId: "009", sprecher: "Person A", text: "Du hast ja damals auch den Fehler gemacht.", kontext: Kontext.Feedback, muster: Muster.Rueckgriff, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Hoch, datum: "2023-10-11T12:00:00Z" },
  { gespraechsId: "009", sprecher: "Person C", text: "Das hat hiermit nichts zu tun. Bleiben wir sachlich.", kontext: Kontext.Feedback, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-11T12:01:00Z" },
  { gespraechsId: "010", sprecher: "Teamleiter", text: "Die Zahlen sehen gut aus.", kontext: Kontext.Allgemein, muster: Muster.Keins, verantwortungUebernommen: "Ja", emotionalitaet: Emotionalitaet.Niedrig, datum: "2023-10-12T17:00:00Z" },
  { gespraechsId: "011", sprecher: "Person C", text: "Wegen der angespannten Marktlage ist das nicht zu schaffen.", kontext: Kontext.Planung, muster: Muster.Relativierung, verantwortungUebernommen: "Nein", emotionalitaet: Emotionalitaet.Mittel, datum: "2023-10-13T09:30:00Z" },
];
